/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TheatrixApp;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Stevan Del Arisandi 1301184365
 */
public class f_Ticket extends javax.swing.JFrame {

    /**
     * Creates new form f_Ticket
     */
    public f_Ticket() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/Image/Icon-Theatrix.png");
        setIconImage(icon.getImage());
        c_Ticket tk = new c_Ticket ();
        
        try {
            if (tk.simpanTiket() !=  null){
                tk.detailTiket(tk.simpanTiket());
                lblID.setText("Ticket ID. "+tk.getIdTransaksi());
                lblUsername.setText("Purchased by "+tk.getUsername());
                lblFilm.setText(tk.getFilm());
                lblPcs.setText(String.valueOf(tk.getPcs())+"Pcs");
                lblHarga.setText("Rp "+String.valueOf(tk.getHarga()));
                lblDate.setText(tk.getDate());
            }
        } catch (SQLException ex) {
            Logger.getLogger(f_Ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblFilm = new javax.swing.JLabel();
        lblPcs = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(21, 151, 133));
        jPanel1.setLayout(null);

        lblID.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 11)); // NOI18N
        lblID.setText("Ticket ID. T000");
        jPanel1.add(lblID);
        lblID.setBounds(230, 240, 130, 14);

        lblUsername.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 11)); // NOI18N
        lblUsername.setText("Purchased by stevandel");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(330, 290, 230, 14);

        lblFilm.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 20)); // NOI18N
        lblFilm.setForeground(new java.awt.Color(255, 255, 255));
        lblFilm.setText("MOVIE TITLE");
        jPanel1.add(lblFilm);
        lblFilm.setBounds(230, 160, 350, 30);

        lblPcs.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 11)); // NOI18N
        lblPcs.setText("00Pcs");
        jPanel1.add(lblPcs);
        lblPcs.setBounds(380, 240, 60, 14);

        lblHarga.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 11)); // NOI18N
        lblHarga.setText("Rp 000.000");
        jPanel1.add(lblHarga);
        lblHarga.setBounds(470, 240, 90, 14);

        lblDate.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 11)); // NOI18N
        lblDate.setText("2021-01-16");
        jPanel1.add(lblDate);
        lblDate.setBounds(230, 290, 90, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ticket.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 50, 750, 300);

        lblBack.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        lblBack.setText(" Back");
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel1.add(lblBack);
        lblBack.setBounds(20, 10, 67, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        f_Transaksi p = new f_Transaksi();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(f_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(f_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(f_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(f_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new f_Ticket().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFilm;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPcs;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
