/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TheatrixApp;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author shidq
 */
public class Frame_Update extends javax.swing.JFrame {

    private boolean gantiProfileCheck = false;
    private boolean gantiPasswordCheck = false;
    private boolean yakinCheck = false;
    /**
     * Creates new form Frame_Update
     * @throws java.sql.SQLException
     */
    public Frame_Update() throws SQLException {
        initComponents();
        ImageIcon icon = new ImageIcon("src/Image/Icon-Theatrix.png");
        setIconImage(icon.getImage());        
        Profile pro = new Profile();
        
        if (pro.simpanProfil() != null ) {
            pro.detailProfil(pro.simpanProfil());
            iNama.setText(pro.getNama());
            if (pro.getGender().equals("Male")){
                rbMale.setSelected(true);
            } else {
                rbFemale.setSelected(true);
            }
            iEmail.setText(pro.getEmail());
            iTelp.setText(pro.getTelp());
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        frameUpdate = new javax.swing.JPanel();
        GantiProfileCheckbox = new javax.swing.JCheckBox();
        GantiPinCheckbox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        labelBack = new javax.swing.JLabel();
        YakinCheckbox = new javax.swing.JCheckBox();
        iNama = new javax.swing.JTextField();
        iEmail = new javax.swing.JTextField();
        iTelp = new javax.swing.JTextField();
        iPassword = new javax.swing.JTextField();
        iConfirmPassword = new javax.swing.JTextField();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frameUpdate.setBackground(new java.awt.Color(21, 151, 133));
        frameUpdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        GantiProfileCheckbox.setBackground(new java.awt.Color(21, 151, 133));
        GantiProfileCheckbox.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        GantiProfileCheckbox.setForeground(new java.awt.Color(255, 255, 255));
        GantiProfileCheckbox.setText("Ganti Profile");
        GantiProfileCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GantiProfileCheckboxActionPerformed(evt);
            }
        });

        GantiPinCheckbox.setBackground(new java.awt.Color(21, 151, 133));
        GantiPinCheckbox.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        GantiPinCheckbox.setForeground(new java.awt.Color(255, 255, 255));
        GantiPinCheckbox.setText("Ganti Password");
        GantiPinCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GantiPinCheckboxActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");

        OKButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OKButton.setText("OK");
        OKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKButtonMouseClicked(evt);
            }
        });

        labelBack.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        labelBack.setForeground(new java.awt.Color(255, 255, 255));
        labelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        labelBack.setText(" Back");
        labelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
        });

        YakinCheckbox.setBackground(new java.awt.Color(21, 151, 133));
        YakinCheckbox.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        YakinCheckbox.setForeground(new java.awt.Color(255, 255, 255));
        YakinCheckbox.setText("Yakin?");
        YakinCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YakinCheckboxActionPerformed(evt);
            }
        });

        iNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        iEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        iTelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        iPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        iConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rbMale.setBackground(new java.awt.Color(21, 151, 133));
        rbMale.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        rbMale.setForeground(new java.awt.Color(255, 255, 255));
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });

        rbFemale.setBackground(new java.awt.Color(21, 151, 133));
        rbFemale.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        rbFemale.setForeground(new java.awt.Color(255, 255, 255));
        rbFemale.setText("Female");
        rbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemaleActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Telp");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Password");

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update Profile");

        javax.swing.GroupLayout frameUpdateLayout = new javax.swing.GroupLayout(frameUpdate);
        frameUpdate.setLayout(frameUpdateLayout);
        frameUpdateLayout.setHorizontalGroup(
            frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameUpdateLayout.createSequentialGroup()
                .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameUpdateLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GantiProfileCheckbox)
                            .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(iEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iNama, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(frameUpdateLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)))
                    .addGroup(frameUpdateLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(rbMale)
                        .addGap(26, 26, 26)
                        .addComponent(rbFemale)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(frameUpdateLayout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(GantiPinCheckbox)
                            .addGap(128, 128, 128))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameUpdateLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(317, 317, 317)))
                    .addGroup(frameUpdateLayout.createSequentialGroup()
                        .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frameUpdateLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(iConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
            .addGroup(frameUpdateLayout.createSequentialGroup()
                .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameUpdateLayout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(YakinCheckbox))
                    .addGroup(frameUpdateLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameUpdateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelBack)
                        .addGap(245, 245, 245)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameUpdateLayout.setVerticalGroup(
            frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameUpdateLayout.createSequentialGroup()
                .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GantiProfileCheckbox)
                            .addComponent(GantiPinCheckbox))
                        .addGap(30, 30, 30)
                        .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(iNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbFemale)
                            .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbMale)
                                .addComponent(jLabel5))))
                    .addGroup(frameUpdateLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(8, 8, 8)
                .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(iEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(frameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(iTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(YakinCheckbox)
                .addGap(18, 18, 18)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(833, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GantiPinCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GantiPinCheckboxActionPerformed
        // TODO add your handling code here:
        gantiPasswordCheck = true;
    }//GEN-LAST:event_GantiPinCheckboxActionPerformed

    private void GantiProfileCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GantiProfileCheckboxActionPerformed
        // TODO add your handling code here:
        gantiProfileCheck = true;
    }//GEN-LAST:event_GantiProfileCheckboxActionPerformed

    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        try {
            Frame_PROFILE p = new Frame_PROFILE();
            p.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Frame_Update.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelBackMouseClicked

    private void OKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKButtonMouseClicked
        // TODO add your handling code here:
        try {
            Update up = new Update();
            //Login profil = new Login();
            Frame_Update stay = new Frame_Update();
            Frame_PROFILE next = new Frame_PROFILE();
            f_Home back = new f_Home();
            if (yakinCheck){
                
                if (gantiProfileCheck){
                    try {
                        String gender = "";
                        if(rbMale.isSelected()){
                            gender = rbMale.getText();
                        }else
                            gender = rbFemale.getText();
                        
                        up.updateMember(iNama.getText(), gender, iEmail.getText(), iTelp.getText());

                        //profil.simpanLogin(iNoHp.getText());
                         JOptionPane.showMessageDialog(null, "Data Profil Berhasil Diubah");
                         back.setVisible(true);
                         back.pack();
//                         next.setVisible(true);
//                         next.pack();
                         this.dispose();
                    } catch (SQLException ex) {
                        Logger.getLogger(Frame_Update.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (gantiPasswordCheck){
                    Profile prof = new Profile(); 
                    prof.detailProfil(prof.simpanProfil());
//                    boolean angka = true;
//                    
//                    try {
//                        double a = Double.parseDouble(iPin.getText());
//                    } catch (Exception e) {
//                        angka = false;
//                    }
//                    
//                    if (angka) {
                        if (iPassword.getText().length() < 8 || iPassword.getText().length() > 16){
                            JOptionPane.showMessageDialog(null, "Password Length must be minimum 8 characters and maximum 16 characters!");  
                           
                            stay.setVisible(true);
                            stay.pack();
                            this.dispose();
                        }else {
                            if (!iPassword.getText().equals(iConfirmPassword.getText())){
                                JOptionPane.showMessageDialog(null, "Password Confirmation did not match!");
                                
                                stay.setVisible(true);
                                stay.pack();
                                this.dispose();
                            } else {
                                up.UpdatePassword(prof.getUsername(), iPassword.getText());
                                JOptionPane.showMessageDialog(null, "Password successfully changed");
                                back.setVisible(true);
                                back.pack();
//                                next.setVisible(true);
//                                next.pack();
                                this.dispose();
                                
                            }
                        }
//                    } else {
//                        JOptionPane.showMessageDialog(null, "PIN HARUS ANGKA!");
//                        
//                        stay.setVisible(true);
//                        stay.pack();
//                        this.dispose();
//                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Klik Yakin jika memang sudah yakin");
                stay.setVisible(true);
                stay.pack();
                this.dispose();
            }
            
           
//            Frame_PROFILE p = new Frame_PROFILE();
//            p.setVisible(true);
//            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(Frame_Update.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OKButtonMouseClicked

    private void YakinCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YakinCheckboxActionPerformed
        yakinCheck = true;
    }//GEN-LAST:event_YakinCheckboxActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        rbFemale.setSelected(false);
    }//GEN-LAST:event_rbMaleActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        rbMale.setSelected(false);
    }//GEN-LAST:event_rbFemaleActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frame_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frame_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frame_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frame_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new Frame_Update().setVisible(true);
//                } catch (SQLException ex) {
//                    Logger.getLogger(Frame_Update.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox GantiPinCheckbox;
    private javax.swing.JCheckBox GantiProfileCheckbox;
    private javax.swing.JButton OKButton;
    private javax.swing.JCheckBox YakinCheckbox;
    private javax.swing.JPanel frameUpdate;
    private javax.swing.JTextField iConfirmPassword;
    private javax.swing.JTextField iEmail;
    private javax.swing.JTextField iNama;
    private javax.swing.JTextField iPassword;
    private javax.swing.JTextField iTelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelBack;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    // End of variables declaration//GEN-END:variables
}
